#ifndef HPC_PARAMETERS_HPP_
#define HPC_PARAMETERS_HPP_

#include "parameter.hpp"

namespace param
{
enum class ParameterID : param::ParamIndex
{
    MC_PWM_DEADBAND = 0U,
    MC_RATE_STIFFNESS,
    MC_RATE_DAMPING,
    MC_UNDERVOLTAGE_FAULT_THRESHOLD,
    MC_OVERVOLTAGE_FAULT_THRESHOLD,
    BATTERY_DISCHARGE_CURVE_C0,
    BATTERY_DISCHARGE_CURVE_C1,
    BATTERY_DISCHARGE_CURVE_C2,
    BATTERY_DISCHARGE_CURVE_C3,
    CLI_UPDATE_FREQ,
    NUM_PARAMS,  // keep this at the end
};
}

#endif
